-- Set schema
CREATE SCHEMA IF NOT EXISTS CONCASSE;
SET SCHEMA CONCASSE;

-- Create tables structure
CREATE TABLE SERVER (SERVER_ID integer NOT NULL, NOM varchar(100) NOT NULL, BRIFUS_ID integer NOT NULL);
CREATE TABLE ITEM_TYPE (TYPE_ID integer NOT NULL, NOM varchar(100) NOT NULL);
CREATE TABLE ITEM (VULBIS_ID integer NOT NULL, BRIFUS_ID integer NOT NULL, NOM varchar(100) NOT NULL, TYPE_ID integer NOT NULL);
CREATE TABLE PRICE (VULBIS_ID integer NOT NULL,	PRICE_HUNDRED integer, SERVER_ID integer NOT NULL, PRICE_TEN integer, PRICE_ONE integer, LAST_UPDATE_DATE timestamp NOT NULL);
CREATE TABLE STAT (STAT_ID integer NOT NULL, STAT_NAME integer NOT NULL);
CREATE TABLE STAT_ITEM ( STAT_LOWER integer NOT NULL, STAT_UPPER integer NOT NULL, VULBIS_ID integer NOT NULL, STAT_ID integer NOT NULL);
CREATE TABLE RUNE (VULBIS_ID integer NOT NULL, STAT_ID integer NOT NULL, TIER integer NOT NULL, WEIGHT integer NOT NULL);
CREATE TABLE TX_BRISAGE (VULBIS_ID integer NOT NULL, SERVER_ID integer NOT NULL, TAUX integer, LAST_UPDATE_DATE timestamp);
CREATE TABLE METIER (METIER_ID integer NOT NULL, METIER_LABEL varchar(50));
CREATE TABLE METIER_PEUT_CRAFT (METIER_ID integer NOT NULL,	TYPE_ID integer NOT NULL);
CREATE TABLE RECIPE (VULBIS_ID_CRAFT integer NOT NULL, QUANTITY integer NOT NULL, VULBIS_ID_COMPONENT integer NOT NULL);
CREATE TABLE NIVEAU_METIER (METIER_ID integer NOT NULL, SERVER_ID integer NOT NULL,	NIVEAU integer NOT NULL);

-- Set PKs
ALTER TABLE RECIPE ADD PRIMARY KEY (VULBIS_ID_CRAFT,VULBIS_ID_COMPONENT);
ALTER TABLE METIER ADD PRIMARY KEY (METIER_ID);
ALTER TABLE STAT ADD PRIMARY KEY (STAT_ID);
ALTER TABLE ITEM ADD PRIMARY KEY (VULBIS_ID);
ALTER TABLE ITEM_TYPE ADD PRIMARY KEY (TYPE_ID);
ALTER TABLE SERVER ADD PRIMARY KEY (SERVER_ID);

-- Set FKs
ALTER TABLE ITEM ADD CONSTRAINT FK_ITEM_ITEMTYPE FOREIGN KEY (TYPE_ID) REFERENCES ITEM_TYPE(TYPE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE PRICE ADD CONSTRAINT FK_PRICE_SERVER FOREIGN KEY (SERVER_ID) REFERENCES SERVER(SERVER_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE PRICE ADD CONSTRAINT FK_PRICE_ITEM FOREIGN KEY (VULBIS_ID) REFERENCES ITEM(VULBIS_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE RUNE ADD CONSTRAINT FK_RUNE_ITEM FOREIGN KEY (VULBIS_ID) REFERENCES ITEM(VULBIS_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE RUNE ADD CONSTRAINT FK_RUNE_STAT FOREIGN KEY (STAT_ID) REFERENCES STAT(STAT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE STAT_ITEM ADD CONSTRAINT FK_STAT_ITEM_ITEM FOREIGN KEY (VULBIS_ID) REFERENCES ITEM(VULBIS_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE STAT_ITEM ADD CONSTRAINT FK_STAT_ITEM_STAT FOREIGN KEY (STAT_ID) REFERENCES STAT(STAT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TX_BRISAGE ADD CONSTRAINT FK_SERVER_TX_BRISAGE FOREIGN KEY (SERVER_ID) REFERENCES SERVER(SERVER_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TX_BRISAGE ADD CONSTRAINT FK_TX_BRISAGE_SERVER FOREIGN KEY (VULBIS_ID) REFERENCES ITEM(VULBIS_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE METIER_PEUT_CRAFT ADD CONSTRAINT FK_METIER_METIER_CRAFT FOREIGN KEY (METIER_ID) REFERENCES METIER(METIER_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE METIER_PEUT_CRAFT ADD CONSTRAINT FK_ITEM_TYPE_METIER_CRAFT FOREIGN KEY (TYPE_ID) REFERENCES ITEM_TYPE(TYPE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE RECIPE ADD CONSTRAINT FK_RECIPE_TARGET FOREIGN KEY (VULBIS_ID_CRAFT) REFERENCES ITEM(VULBIS_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE RECIPE ADD CONSTRAINT FK_ITEM_COMPO FOREIGN KEY (VULBIS_ID_COMPONENT) REFERENCES ITEM(VULBIS_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE NIVEAU_METIER ADD CONSTRAINT FK_METIER_NIVEAU_METIER FOREIGN KEY (METIER_ID) REFERENCES METIER(METIER_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE NIVEAU_METIER ADD CONSTRAINT FK_METIER_SERVER FOREIGN KEY (SERVER_ID) REFERENCES SERVER(SERVER_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;