-- SERVER
INSERT INTO SERVER (SERVER_ID, NOM, BRIFUS_ID) VALUES (1, "Draconiros", 2);
INSERT INTO SERVER (SERVER_ID, NOM, BRIFUS_ID) VALUES (2, "Hell Mina", 5);
INSERT INTO SERVER (SERVER_ID, NOM, BRIFUS_ID) VALUES (3, "Imagiro", 6);
INSERT INTO SERVER (SERVER_ID, NOM, BRIFUS_ID) VALUES (4, "Ombre", 7);
INSERT INTO SERVER (SERVER_ID, NOM, BRIFUS_ID) VALUES (5, "Orukam", 3);
INSERT INTO SERVER (SERVER_ID, NOM, BRIFUS_ID) VALUES (6, "Tal Kasha", 4);
INSERT INTO SERVER (SERVER_ID, NOM, BRIFUS_ID) VALUES (7, "Tylezia", 1);

-- ITEM_TYPE





-- METIER
INSERT INTO METIER (METIER_ID, TYPE_ID) VALUES (1, "Alchimiste");
INSERT INTO METIER (METIER_ID, TYPE_ID) VALUES (2, "Bijoutier");
INSERT INTO METIER (METIER_ID, TYPE_ID) VALUES (3, "Bricoleur");
INSERT INTO METIER (METIER_ID, TYPE_ID) VALUES (4, "Bûcheron");
INSERT INTO METIER (METIER_ID, TYPE_ID) VALUES (5, "Chasseur");
INSERT INTO METIER (METIER_ID, TYPE_ID) VALUES (6, "Cordonnier");
INSERT INTO METIER (METIER_ID, TYPE_ID) VALUES (7, "Façonneur");
INSERT INTO METIER (METIER_ID, TYPE_ID) VALUES (8, "Forgeron");
INSERT INTO METIER (METIER_ID, TYPE_ID) VALUES (9, "Mineur");
INSERT INTO METIER (METIER_ID, TYPE_ID) VALUES (10, "Paysan");
INSERT INTO METIER (METIER_ID, TYPE_ID) VALUES (11, "Pêcheur");
INSERT INTO METIER (METIER_ID, TYPE_ID) VALUES (12, "Sculpteur");
INSERT INTO METIER (METIER_ID, TYPE_ID) VALUES (13, "Tailleur");













-- METIER_PEUT_CRAFT
-- NIVEAU_METIER (Tout a 0)
-- STAT