-- Create tables structure
CREATE TABLE SERVER (SERVER_ID integer NOT NULL, NOM varchar(100) NOT NULL, BRIFUS_ID integer NOT NULL);
CREATE TABLE ITEM_TYPE (TYPE_ID integer NOT NULL, NOM varchar(100) NOT NULL);
CREATE TABLE ITEM (VULBIS_ID integer NOT NULL, NOM varchar(100) NOT NULL, TYPE_ID integer NOT NULL, LEVEL integer NOT NULL, EST_CONCASSABLE boolean NOT NULL);
CREATE TABLE PRICE (VULBIS_ID integer NOT NULL, SERVER_ID integer NOT NULL,	PRICE_ONE integer, PRICE_TEN integer, PRICE_HUNDRED integer, LAST_REFRESH_DATE varchar(100), LAST_PRICE_UPDATE_DATE varchar(100));
CREATE TABLE STAT (STAT_ID integer NOT NULL, STAT_NAME varchar(100) NOT NULL);
CREATE TABLE STAT_ITEM ( STAT_LOWER integer NOT NULL, STAT_UPPER integer NOT NULL, ITEM_ID_VULBIS integer NOT NULL, STAT_ID integer NOT NULL);
CREATE TABLE RUNE (VULBIS_ID integer NOT NULL, STAT_ID integer NOT NULL, TIER integer NOT NULL, WEIGHT float NOT NULL);
CREATE TABLE TX_BRISAGE (VULBIS_ID integer NOT NULL, SERVER_ID integer NOT NULL, TAUX integer, LAST_REFRESH_DATE varchar(100), LAST_TX_UPDATE_DATE varchar(100));
CREATE TABLE METIER (METIER_ID integer NOT NULL, METIER_LABEL varchar(50));
CREATE TABLE METIER_PEUT_CRAFT (METIER_ID integer NOT NULL,	TYPE_ID integer NOT NULL);
CREATE TABLE RECIPE (VULBIS_ID_CRAFT integer NOT NULL, VULBIS_ID_COMPONENT integer NOT NULL, QUANTITY integer NOT NULL);
CREATE TABLE NIVEAU_METIER (METIER_ID integer NOT NULL, SERVER_ID integer NOT NULL,	NIVEAU integer NOT NULL);

-- Set PKs
ALTER TABLE RECIPE ADD PRIMARY KEY (VULBIS_ID_CRAFT,VULBIS_ID_COMPONENT);
ALTER TABLE METIER ADD PRIMARY KEY (METIER_ID);
ALTER TABLE METIER_PEUT_CRAFT ADD PRIMARY KEY (METIER_ID, TYPE_ID);
ALTER TABLE RUNE ADD PRIMARY KEY (VULBIS_ID);
ALTER TABLE STAT ADD PRIMARY KEY (STAT_ID);
ALTER TABLE ITEM ADD PRIMARY KEY (VULBIS_ID);
ALTER TABLE ITEM_TYPE ADD PRIMARY KEY (TYPE_ID);
ALTER TABLE SERVER ADD PRIMARY KEY (SERVER_ID);
ALTER TABLE PRICE ADD PRIMARY KEY (VULBIS_ID, SERVER_ID);
ALTER TABLE STAT_ITEM ADD PRIMARY KEY (ITEM_ID_VULBIS, STAT_ID);
ALTER TABLE TX_BRISAGE ADD PRIMARY KEY (VULBIS_ID, SERVER_ID);